import type { TriggerKeySnapshot } from "../../triggers/common/types.ts";

import { jsonSchema as s } from "../../core/json-schema.ts";
const events: readonly string[] = [
  "*",
  "branch_protection_configuration",
  "branch_protection_rule",
  "check_run",
  "check_suite",
  "code_scanning_alert",
  "commit_comment",
  "create",
  "custom_property_values",
  "delete",
  "dependabot_alert",
  "deploy_key",
  "deployment",
  "deployment_status",
  "discussion",
  "discussion_comment",
  "fork",
  "gollum",
  "issue_comment",
  "issue_dependencies",
  "issues",
  "label",
  "member",
  "meta",
  "milestone",
  "package",
  "page_build",
  "project",
  "project_card",
  "project_column",
  "public",
  "pull_request",
  "pull_request_review",
  "pull_request_review_comment",
  "pull_request_review_thread",
  "push",
  "registry_package",
  "release",
  "repository",
  "repository_advisory",
  "repository_import",
  "repository_ruleset",
  "repository_vulnerability_alert",
  "secret_scanning_alert",
  "secret_scanning_alert_location",
  "secret_scanning_scan",
  "security_and_analysis",
  "star",
  "status",
  "sub_issues",
  "team_add",
  "watch",
  "workflow_job",
  "workflow_run",
] as const;
export const snapshot: TriggerKeySnapshot & { readonly type: "integration" } = {
  configInputs: [
    {
      handle: "events",
      jsonSchema: s.array(s.stringEnum(events), { minItems: 1, uniqueItems: true }),
      nullable: false,
    },
    { handle: "insecureSsl", jsonSchema: s.boolean(), nullable: false, value: false },
    {
      handle: "owner",
      jsonSchema: s.string({ pattern: "^[a-zA-Z0-9](?:[a-zA-Z0-9]|-(?=[a-zA-Z0-9])){0,38}$" }),
      nullable: false,
    },
    {
      handle: "repo",
      jsonSchema: s.string({ pattern: "^(?!\\.{1,2}$)[a-zA-Z0-9._-]{1,100}$" }),
      nullable: false,
    },
  ],
  definitionVersion: 2,
  description: "Triggers when selected GitHub webhook events occur in a repository.",
  displayName: "Repository Event",
  endpoint: {
    body: { allowArray: false, allowEmpty: false, formats: ["json"] },
    methods: ["POST"],
    successStatus: 202,
  },
  key: "github.on_repo_event",
  name: "on_repo_event",
  outputs: [
    { handle: "body", jsonSchema: { type: "object" }, nullable: false },
    { handle: "deliveryId", jsonSchema: s.string(), nullable: false },
    { handle: "event", jsonSchema: s.string(), nullable: false },
  ],
  provider: "github",
  type: "integration",
};
