export const keepaDealAttributeNames = [
  "material",
  "type",
  "manufacturer",
  "brand",
  "model",
  "color",
  "size",
  "unitType",
  "scent",
  "itemForm",
  "pattern",
  "style",
  "itemTypeKeyword",
  "targetAudienceKeyword",
  "edition",
  "format",
  "author",
  "binding",
  "languages",
  "brandStoreName",
  "brandStoreUrlName",
  "websiteDisplayGroup",
  "websiteDisplayGroupName",
  "salesRankDisplayGroup",
] as const;
