import type { TriggerKeySnapshot } from "../../triggers/common/types.ts";

import { jsonSchema as s } from "../../core/json-schema.ts";
const topics: readonly string[] = [
  "app/scopes_update",
  "app/uninstalled",
  "app_purchases_one_time/update",
  "app_subscriptions/approaching_capped_amount",
  "app_subscriptions/update",
  "bulk_operations/finish",
  "carts/create",
  "carts/update",
  "channels/delete",
  "checkout_and_accounts_configurations/update",
  "checkouts/create",
  "checkouts/delete",
  "checkouts/update",
  "collection_listings/add",
  "collection_listings/remove",
  "collection_listings/update",
  "collection_publications/create",
  "collection_publications/delete",
  "collection_publications/update",
  "collections/create",
  "collections/delete",
  "collections/update",
  "companies/create",
  "companies/delete",
  "companies/update",
  "company_contact_roles/assign",
  "company_contact_roles/revoke",
  "company_contacts/create",
  "company_contacts/delete",
  "company_contacts/update",
  "company_locations/create",
  "company_locations/delete",
  "company_locations/update",
  "customer.joined_segment",
  "customer.left_segment",
  "customer.tags_added",
  "customer.tags_removed",
  "customer_account_settings/update",
  "customer_groups/create",
  "customer_groups/delete",
  "customer_groups/update",
  "customers/create",
  "customers/delete",
  "customers/disable",
  "customers/enable",
  "customers/purchasing_summary",
  "customers/update",
  "customers_email_marketing_consent/update",
  "customers_marketing_consent/update",
  "delivery_promise_settings/update",
  "disputes/create",
  "disputes/update",
  "domains/create",
  "domains/destroy",
  "domains/update",
  "draft_orders/create",
  "draft_orders/delete",
  "draft_orders/update",
  "fulfillment_events/create",
  "fulfillment_events/delete",
  "fulfillment_holds/added",
  "fulfillment_holds/released",
  "fulfillment_orders/cancellation_request_accepted",
  "fulfillment_orders/cancellation_request_rejected",
  "fulfillment_orders/cancellation_request_submitted",
  "fulfillment_orders/cancelled",
  "fulfillment_orders/fulfillment_request_accepted",
  "fulfillment_orders/fulfillment_request_rejected",
  "fulfillment_orders/fulfillment_request_submitted",
  "fulfillment_orders/fulfillment_service_failed_to_complete",
  "fulfillment_orders/hold_released",
  "fulfillment_orders/line_items_prepared_for_local_delivery",
  "fulfillment_orders/line_items_prepared_for_pickup",
  "fulfillment_orders/manually_reported_progress_stopped",
  "fulfillment_orders/merged",
  "fulfillment_orders/moved",
  "fulfillment_orders/order_routing_complete",
  "fulfillment_orders/placed_on_hold",
  "fulfillment_orders/progress_reported",
  "fulfillment_orders/rescheduled",
  "fulfillment_orders/scheduled_fulfillment_order_ready",
  "fulfillment_orders/split",
  "fulfillments/create",
  "fulfillments/update",
  "inventory_items/create",
  "inventory_items/delete",
  "inventory_items/update",
  "inventory_levels/connect",
  "inventory_levels/disconnect",
  "inventory_levels/update",
  "locales/create",
  "locales/destroy",
  "locales/update",
  "locations/activate",
  "locations/create",
  "locations/deactivate",
  "locations/delete",
  "locations/update",
  "machine_translation_batch/completed",
  "metafield_definitions/create",
  "metafield_definitions/delete",
  "metafield_definitions/update",
  "order_transactions/create",
  "orders/cancelled",
  "orders/create",
  "orders/delete",
  "orders/edited",
  "orders/fulfilled",
  "orders/link_requested",
  "orders/paid",
  "orders/partially_fulfilled",
  "orders/risk_assessment_changed",
  "orders/shopify_protect_eligibility_changed",
  "orders/updated",
  "payment_schedules/due",
  "payment_terms/create",
  "payment_terms/delete",
  "payment_terms/update",
  "product_feeds/create",
  "product_feeds/full_sync",
  "product_feeds/full_sync_finish",
  "product_feeds/incremental_sync",
  "product_feeds/update",
  "product_listings/add",
  "product_listings/remove",
  "product_listings/update",
  "product_publications/create",
  "product_publications/delete",
  "product_publications/update",
  "products/create",
  "products/delete",
  "products/update",
  "profiles/create",
  "profiles/delete",
  "profiles/update",
  "publications/delete",
  "refunds/create",
  "returns/approve",
  "returns/cancel",
  "returns/close",
  "returns/decline",
  "returns/process",
  "returns/reopen",
  "returns/request",
  "returns/update",
  "reverse_deliveries/attach_deliverable",
  "reverse_fulfillment_orders/dispose",
  "scheduled_product_listings/add",
  "scheduled_product_listings/remove",
  "scheduled_product_listings/update",
  "segments/create",
  "segments/delete",
  "segments/update",
  "selling_plan_groups/create",
  "selling_plan_groups/delete",
  "selling_plan_groups/update",
  "shop/update",
  "subscription_billing_attempts/challenged",
  "subscription_billing_attempts/failure",
  "subscription_billing_attempts/success",
  "subscription_billing_cycle_edits/create",
  "subscription_billing_cycle_edits/delete",
  "subscription_billing_cycle_edits/update",
  "subscription_billing_cycles/skip",
  "subscription_billing_cycles/unskip",
  "subscription_contracts/activate",
  "subscription_contracts/cancel",
  "subscription_contracts/create",
  "subscription_contracts/expire",
  "subscription_contracts/fail",
  "subscription_contracts/pause",
  "subscription_contracts/update",
  "tax_partners/update",
  "tax_summaries/create",
  "tender_transactions/create",
  "themes/create",
  "themes/delete",
  "themes/publish",
  "themes/update",
  "variants/in_stock",
  "variants/out_of_stock",
] as const;
export const snapshot: TriggerKeySnapshot & { readonly type: "integration" } = {
  configInputs: [
    {
      handle: "topics",
      jsonSchema: s.array(s.stringEnum(topics), { maxItems: 20, minItems: 1, uniqueItems: true }),
      nullable: false,
    },
  ],
  definitionVersion: 2,
  description: "Triggers when selected Shopify webhook topics occur in the connected store.",
  displayName: "Store Event",
  endpoint: {
    body: { allowArray: false, allowEmpty: false, formats: ["json"] },
    methods: ["POST"],
    successStatus: 202,
  },
  key: "shopify.on_shop_event",
  name: "on_shop_event",
  outputs: [
    { handle: "apiVersion", jsonSchema: s.string(), nullable: false },
    { handle: "body", jsonSchema: { type: "object" }, nullable: false },
    { handle: "eventId", jsonSchema: s.string(), nullable: false },
    { handle: "shopDomain", jsonSchema: s.string(), nullable: false },
    { handle: "topic", jsonSchema: s.string(), nullable: false },
    { handle: "triggeredAt", jsonSchema: s.string(), nullable: false },
    { handle: "webhookId", jsonSchema: s.string(), nullable: false },
  ],
  provider: "shopify",
  type: "integration",
};
