import type { TriggerKeySnapshot } from "../../triggers/common/types.ts";

import { jsonSchema as s } from "../../core/json-schema.ts";
const events: readonly string[] = [
  "zen:event-type:ticket.agent_assignment_changed",
  "zen:event-type:ticket.attachment_linked_to_comment",
  "zen:event-type:ticket.attachment_redacted_from_comment",
  "zen:event-type:ticket.brand_changed",
  "zen:event-type:ticket.comment_added",
  "zen:event-type:ticket.comment_made_private",
  "zen:event-type:ticket.comment_redacted",
  "zen:event-type:ticket.created",
  "zen:event-type:ticket.csat_received",
  "zen:event-type:ticket.csat_requested",
  "zen:event-type:ticket.custom_field_changed",
  "zen:event-type:ticket.custom_status_changed",
  "zen:event-type:ticket.description_changed",
  "zen:event-type:ticket.email_ccs_changed",
  "zen:event-type:ticket.external_id_changed",
  "zen:event-type:ticket.followers_changed",
  "zen:event-type:ticket.form_changed",
  "zen:event-type:ticket.group_assignment_changed",
  "zen:event-type:ticket.marked_as_spam",
  "zen:event-type:ticket.merged",
  "zen:event-type:ticket.next_sla_breach_changed",
  "zen:event-type:ticket.ola_policy_changed",
  "zen:event-type:ticket.organization_changed",
  "zen:event-type:ticket.permanently_deleted",
  "zen:event-type:ticket.priority_changed",
  "zen:event-type:ticket.problem_link_changed",
  "zen:event-type:ticket.requester_changed",
  "zen:event-type:ticket.schedule_changed",
  "zen:event-type:ticket.sla_policy_changed",
  "zen:event-type:ticket.soft_deleted",
  "zen:event-type:ticket.status_changed",
  "zen:event-type:ticket.subject_changed",
  "zen:event-type:ticket.submitter_changed",
  "zen:event-type:ticket.tags_changed",
  "zen:event-type:ticket.task_due_at_changed",
  "zen:event-type:ticket.type_changed",
  "zen:event-type:ticket.undeleted",
  "zen:event-type:organization.created",
  "zen:event-type:organization.custom_field_changed",
  "zen:event-type:organization.deleted",
  "zen:event-type:organization.external_id_changed",
  "zen:event-type:organization.name_changed",
  "zen:event-type:organization.tags_changed",
  "zen:event-type:user.active_changed",
  "zen:event-type:user.alias_changed",
  "zen:event-type:user.created",
  "zen:event-type:user.custom_field_changed",
  "zen:event-type:user.custom_role_changed",
  "zen:event-type:user.default_group_changed",
  "zen:event-type:user.deleted",
  "zen:event-type:user.details_changed",
  "zen:event-type:user.external_id_changed",
  "zen:event-type:user.group_membership_created",
  "zen:event-type:user.group_membership_deleted",
  "zen:event-type:user.identity_changed",
  "zen:event-type:user.identity_created",
  "zen:event-type:user.identity_deleted",
  "zen:event-type:user.last_login_changed",
  "zen:event-type:user.merged",
  "zen:event-type:user.name_changed",
  "zen:event-type:user.notes_changed",
  "zen:event-type:user.only_private_comments_changed",
  "zen:event-type:user.organization_membership_created",
  "zen:event-type:user.organization_membership_deleted",
  "zen:event-type:user.password_changed",
  "zen:event-type:user.photo_changed",
  "zen:event-type:user.role_changed",
  "zen:event-type:user.suspended_changed",
  "zen:event-type:user.tags_changed",
  "zen:event-type:user.time_zone_changed",
] as const;
export const endpoint: string = "/api/v2/webhooks";
export const snapshot: TriggerKeySnapshot & { readonly type: "integration" } = {
  configInputs: [
    {
      handle: "events",
      jsonSchema: s.array(s.stringEnum(events), { minItems: 1, uniqueItems: true }),
      nullable: false,
    },
  ],
  definitionVersion: 2,
  description: "Triggers when one of the selected Zendesk account events occurs.",
  displayName: "Event Subscription",
  endpoint: {
    body: { allowArray: false, allowEmpty: false, formats: ["json"] },
    methods: ["POST"],
    successStatus: 202,
  },
  key: "zendesk.on_event",
  name: "on_event",
  outputs: [
    { handle: "body", jsonSchema: { type: "object" }, nullable: false },
    { handle: "deliveryId", jsonSchema: s.string(), nullable: false },
    { handle: "event", jsonSchema: s.string(), nullable: false },
    { handle: "subject", jsonSchema: s.string(), nullable: false },
  ],
  provider: "zendesk",
  type: "integration",
};
