import type { TriggerKeySnapshot } from "../../triggers/common/types.ts";

import { jsonSchema as s } from "../../core/json-schema.ts";
export const updateTypes: readonly string[] = [
  "*",
  "message",
  "edited_message",
  "channel_post",
  "edited_channel_post",
  "business_connection",
  "business_message",
  "edited_business_message",
  "deleted_business_messages",
  "guest_message",
  "message_reaction",
  "message_reaction_count",
  "inline_query",
  "chosen_inline_result",
  "callback_query",
  "shipping_query",
  "pre_checkout_query",
  "purchased_paid_media",
  "poll",
  "poll_answer",
  "my_chat_member",
  "chat_member",
  "chat_join_request",
  "chat_boost",
  "removed_chat_boost",
  "managed_bot",
  "subscription",
] as const;
export const snapshot: TriggerKeySnapshot & { readonly type: "integration" } = {
  configInputs: [
    {
      handle: "chatIds",
      jsonSchema: s.array(s.string({ pattern: "^-?[0-9]{1,20}$" }), { maxItems: 100, uniqueItems: true }),
      nullable: false,
      value: [],
      description: "Only accept updates from these numeric Telegram chat IDs. Empty means every chat.",
    },
    {
      handle: "dropPendingUpdates",
      jsonSchema: s.boolean(),
      nullable: false,
      value: true,
      description: "Discard updates queued before the webhook is created or resumed.",
    },
    {
      handle: "updates",
      jsonSchema: s.array({ enum: updateTypes }, { minItems: 1, uniqueItems: true }),
      nullable: false,
      description: "Telegram update types that trigger a Run. Use * for the Telegram default set.",
    },
    {
      handle: "userIds",
      jsonSchema: s.array(s.string({ pattern: "^[0-9]{1,20}$" }), { maxItems: 100, uniqueItems: true }),
      nullable: false,
      value: [],
      description: "Only accept updates from these numeric Telegram user IDs. Empty means every user.",
    },
  ],
  definitionVersion: 2,
  description: "Triggers when the connected Telegram bot receives a selected update.",
  displayName: "Bot Update",
  endpoint: {
    body: { allowArray: false, allowEmpty: false, formats: ["json"] },
    methods: ["POST"],
    successStatus: 200,
  },
  key: "telegram.on_update",
  name: "on_update",
  outputs: [
    { handle: "body", jsonSchema: { type: "object" }, nullable: false },
    { handle: "deliveryId", jsonSchema: s.string(), nullable: false },
    { handle: "event", jsonSchema: s.string(), nullable: false },
  ],
  provider: "telegram",
  type: "integration",
};
